[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "al-ghani-pos"
version = "1.0.0"
description = "AL GHANI Restaurant POS backend"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]==0.111.0",
    "passlib[bcrypt]==1.7.4",
    "python-jose[cryptography]==3.3.0",
    "pydantic==2.8.0",
    "sqlalchemy==2.0.31",
    "alembic==1.13.1",
    "python-dotenv==1.0.1",
]

[tool.setuptools]
packages = ["app"]

[tool.fastapi]
entrypoint = "app.main:app"
